[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.1"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "hugo --gc --minify"

# Optional: Add custom headers for better caching
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "max-age=3600" 