# Tech Flash Report - Netlify Configuration

[build]
  # Build command runs the RSS aggregator to generate fresh content
  command = "python3 aggregator.py"
  publish = "."
  
[build.environment]
  PYTHON_VERSION = "3.13"
  
# Install Python dependencies
[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true

# Redirects for clean URLs and topic pages
[[redirects]]
  # Redirect old topic pages to new topics/ directory
  from = "/startup-funding.html"
  to = "/topics/startup-funding.html"
  status = 301

[[redirects]]
  from = "/product-launches.html"  
  to = "/topics/product-launches.html"
  status = 301

[[redirects]]
  from = "/enterprise-software.html"
  to = "/topics/enterprise-software.html"
  status = 301

[[redirects]]
  from = "/developer-tools.html"
  to = "/topics/developer-tools.html"
  status = 301

[[redirects]]
  from = "/big-tech-moves.html"
  to = "/topics/big-tech-moves.html"
  status = 301

[[redirects]]
  from = "/ipos-acquisitions.html"
  to = "/topics/ipos-acquisitions.html"
  status = 301

[[redirects]]
  from = "/tech-news-today.html"
  to = "/topics/tech-news-today.html"
  status = 301

[[redirects]]
  from = "/tech-breakthrough-news.html"
  to = "/topics/tech-breakthrough-news.html"
  status = 301

# Clean URL redirects (remove .html extension)
[[redirects]]
  from = "/topics/*"
  to = "/topics/:splat.html"
  status = 200

[[redirects]]
  from = "/archive/*"
  to = "/archive/:splat.html"
  status = 200

# Newsletter form submission
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Contact form submission  
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache headers for static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML cache (shorter for fresh content)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# RSS and JSON feeds
[[headers]]
  for = "*.xml"
  [headers.values]
    Cache-Control = "public, max-age=1800"
    Content-Type = "application/rss+xml; charset=utf-8"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=1800"
    Content-Type = "application/json; charset=utf-8"

# Form handling
[forms]
  newsletter = "/thank-you"
  contact = "/contact-success"

# Environment variables (these would be set in Netlify dashboard)
# NEWS_API_KEY = "your_news_api_key_here"
# PERPLEXITY_API_KEY = "your_perplexity_api_key_here"  
# REDDIT_CLIENT_ID = "your_reddit_client_id_here"
# REDDIT_CLIENT_SECRET = "your_reddit_client_secret_here"

# Build hooks for manual rebuilds
# Set up in Netlify dashboard to trigger rebuilds 